const data = [
  {
    id: 1,
    name: "Dr. Rajesh Sharma",
    department: "Computer Science",
    cabin: "Block A - 203",
    email: "rajesh@college.edu",
    phone: "9876543210",
    image: "https://randomuser.me/api/portraits/men/32.jpg",
  },
  {
    id: 2,
    name: "Dr. Neha Verma",
    department: "Electronics",
    cabin: "Block B - 105",
    email: "neha@college.edu",
    phone: "9876543211",
    image: "https://randomuser.me/api/portraits/women/44.jpg",
  },
  {
    id: 3,
    name: "Prof. Amit Singh",
    department: "Mechanical",
    cabin: "Block C - 301",
    email: "amit@college.edu",
    phone: "9876543212",
    image: "https://randomuser.me/api/portraits/men/12.jpg",
  },
  {
    id: 4,
    name: "Dr. Priya Kapoor",
    department: "Mathematics",
    cabin: "Block D - 112",
    email: "priya@college.edu",
    phone: "9876543213",
    image: "https://randomuser.me/api/portraits/women/65.jpg",
  },
  {
    id: 5,
    name: "Dr. Anil Kumar",
    department: "Physics",
    cabin: "Block E - 202",
    email: "anil@college.edu",
    phone: "9876543214",
    image: "https://randomuser.me/api/portraits/men/75.jpg",
  },
  {
    id: 6,
    name: "Prof. Suman Das",
    department: "Chemistry",
    cabin: "Block F - 310",
    email: "suman@college.edu",
    phone: "9876543215",
    image: "https://randomuser.me/api/portraits/women/22.jpg",
  },
  {
    id: 7,
    name: "Dr. Kavita Mishra",
    department: "Biotechnology",
    cabin: "Block A - 115",
    email: "kavita@college.edu",
    phone: "9876543216",
    image: "https://randomuser.me/api/portraits/women/33.jpg",
  },
  {
    id: 8,
    name: "Dr. Arjun Mehta",
    department: "Civil Engineering",
    cabin: "Block C - 210",
    email: "arjun@college.edu",
    phone: "9876543217",
    image: "https://randomuser.me/api/portraits/men/45.jpg",
  },
];

export default data;